name: Release

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 8
      - run: ./gradlew build
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            build/libs/groovy-language-server-all.jar
          tag_name: ${{ github.sha }}
