name: Release

on:
  push:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 8
        if: matrix.os == 'ubuntu-latest'
      - run: ./gradlew build
        if: matrix.os == 'ubuntu-latest'
      - uses: actions/upload-artifact@v4
        with:
          name: groovy-language-server-all
          path: build/libs/groovy-language-server-all.jar
        if: matrix.os == 'ubuntu-latest'
      - run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: groovy-language-server-${{ runner.os }}
          path: target/release/groovy_language_server_wrapper
        if: matrix.os != 'windows-latest'
      - uses: actions/upload-artifact@v4
        with:
          name: groovy-language-server-${{ runner.os }}
          path: target/release/groovy_language_server_wrapper.exe
        if: matrix.os == 'windows-latest'
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
      - run: |
          cp \
            groovy-language-server-all/groovy-language-server-all.jar \
            groovy-language-server-Linux/groovy-language-server-all.jar
          cp \
            groovy-language-server-all/groovy-language-server-all.jar \
            groovy-language-server-Windows/groovy-language-server-all.jar
          cp \
            groovy-language-server-all/groovy-language-server-all.jar \
            groovy-language-server-macOS/groovy-language-server-all.jar
          zip groovy-language-server-Linux groovy-language-server-Linux
          zip groovy-language-server-Windows groovy-language-server-Windows
          zip groovy-language-server-macOS groovy-language-server-macOS
      - id: shorten-sha
        run: |
          sha=$(echo ${{ github.sha }} | cut -c1-7)
          echo "sha=$sha" >> $GITHUB_OUTPUT
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            groovy-language-server-Linux.zip
            groovy-language-server-Windows.zip
            groovy-language-server-macOS.zip
          tag_name: ${{ steps.shorten-sha.outputs.sha }}
